version: '3.8'

services:
  app:
    container_name: app
    build: .
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydb

  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydb
  #   volumes:
  #     - db-data:/var/lib/postgresql/data

volumes:
  db-data:
